version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: shop
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  node-app:
    container_name: shop-node-app
    build: .
    restart: always
    environment:
      DB_USER: postgres
      DB_HOST: postgres-db
      DB_NAME: shop
      DB_PASSWORD: your_password
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
